### ISSUE TITLE
how to use with an argument that does not need a flag?

### ISSUE THREAD

**Issue by tessus** [frankhart2018/sargparse#4]
I am wondering how this can be used for a command like this:

`parse-test [OPTIONS] <ARG-WITHOUT-FLAG>`

For an example I want to use the `rm` commamd:

- `rm file`
- `rm -f file`

P.S.: Is it required to always add a long flag? I understand that you use it for the key in the hash map, but the problem is, one does not always want a long option. Or at least it should be possible to hide it from the help/usage output.

**Comment by frankhart2018** [comment]
Thanks for raising this issue, @tessus. I have found a lot of issues with the current design, and am thinking of redesigning it from the ground up following the ideas from cpython's argparse.

**Comment by tessus** [comment]
Just to clarify. Does this mean that this is currently not possible?

**Comment by frankhart2018** [comment]
That's right
